### ISSUE TITLE
workflow 和vercel deploy错误

### ISSUE THREAD

**Issue by shixiaocaia** [ischaojie/willow#10]
您好，很喜欢您在v2上分享的主题，今天下载下来自己改了改，workflow这一步出了错误，如下图所示，使用的是和您一样的文件
![image](https://user-images.githubusercontent.com/68102662/233787784-fdcf3db1-f1d1-4f5d-8f10-a77e270c533f.png)

此外我也试了vercel部署，出现如下错误，环境变量，是不是需要指定zola版本？
![image](https://user-images.githubusercontent.com/68102662/233787958-3b5e9df9-7b00-4e39-9757-d3257eade1ee.png)

另外还想问下，zola 是否有指令会像hugo，hexo一样，在本地就直接生成包含所有html的public目录呢？

希望作者大大有空的时候解答一下

**Comment by shixiaocaia** [comment]
找到了`zola build`命令生成html文件，但是并没有正确渲染。

**Comment by ischaojie** [comment]
这个 `zola-deploy-action` 0.17.2 版本是有点问题，我用 0.17.1 解决了，参考：https://github.com/ischaojie/blog/blob/main/.github/workflows/ci.yaml

**Comment by ischaojie** [comment]
> 此外我也试了vercel部署，出现如下错误，环境变量，是不是需要指定zola版本？

对，vercel 要指定 zola的版本：https://vercel.com/docs/concepts/deployments/environments#specifying-framework-versions

**Comment by shixiaocaia** [comment]
谢谢回复，我刚才又试了下0.17.1，但还是没有成功
![image](https://user-images.githubusercontent.com/68102662/233817720-ee7351b8-a778-483b-ad3e-1b51b5f02514.png)

**Comment by ischaojie** [comment]
是不是没提供 GITHUB_TOKEN？

**Comment by shixiaocaia** [comment]
> 是不是没提供 GITHUB_TOKEN？

确实是没添加，抱歉不太熟悉相关操作导致的。

但是通过action生成public内容，仍然没有正确渲染，zola serve查看倒是正常的，这是我的仓库地址https://github.com/shixiaocaia/Zola-willow

**Comment by ischaojie** [comment]
> > 是不是没提供 GITHUB_TOKEN？
> 
> 确实是没添加，抱歉不太熟悉相关操作导致的。
> 
> 但是通过action生成public内容，仍然没有正确渲染，zola serve查看倒是正常的，这是我的仓库地址[shixiaocaia/Zola-willow](https://github.com/shixiaocaia/Zola-willow)

应该是因为你 zola 配置的主域名是 https://shixiaocaia.fun ， 但部署到 github page 之后变成了 https://shixiaocaia.github.io/ ， 导致静态资源没法正常加载。

可以加个自定义域名到 github，应该就正常了~

**Comment by shixiaocaia** [comment]
> > > 是不是没提供 GITHUB_TOKEN？
> > 
> > 
> > 确实是没添加，抱歉不太熟悉相关操作导致的。
> > 但是通过action生成public内容，仍然没有正确渲染，zola serve查看倒是正常的，这是我的仓库地址[shixiaocaia/Zola-willow](https://github.com/shixiaocaia/Zola-willow)
> 
> 应该是因为你 zola 配置的主域名是 https://shixiaocaia.fun ， 但部署到 github page 之后变成了 https://shixiaocaia.github.io/ ， 导致静态资源没法正常加载。
> 
> 可以加个自定义域名到 github，应该就正常了~

谢谢，我再试试！
